Resources:
  WebsiteBucket75C24D94:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: ProjectCode
          Value: waqtec
        - Key: Environment
          Value: prod
        - Key: Owner
          Value: mwaqqas
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: waqqastech/WebsiteBucket/Resource
  WebsiteBucketPolicyE10E3262:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteBucket75C24D94
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - CloudfrontOAI
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - WebsiteBucket75C24D94
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: waqqastech/WebsiteBucket/Policy/Resource
  CloudfrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFrontOAIForWaqtec
    Metadata:
      aws:cdk:path: waqqastech/CloudfrontOAI
  CloudFrontDistributionCFDistribution599ADCC4:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - waqqas.tech
          - blog.waqqas.tech
        Comment: waqqas.tech
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 60
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: origin1
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName:
              Fn::GetAtt:
                - WebsiteBucket75C24D94
                - RegionalDomainName
            Id: origin1
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: CloudfrontOAI
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:147218828400:certificate/2e249ec4-2a86-4cc4-a535-ee01f7ba6842
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
      Tags:
        - Key: ProjectCode
          Value: waqtec
        - Key: Environment
          Value: prod
        - Key: Owner
          Value: mwaqqas
    Metadata:
      aws:cdk:path: waqqastech/CloudFrontDistribution/CFDistribution
  PrimaryDNSRecord052CE852:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: waqqas.tech.
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - CloudFrontDistributionCFDistribution599ADCC4
            - DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: waqtec CloudFront Dist Alias Record
      HostedZoneId: Z37WEOKUCYC5ME
    Metadata:
      aws:cdk:path: waqqastech/PrimaryDNSRecord/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.7.0,@aws-cdk/assets=1.7.0,@aws-cdk/aws-apigateway=1.7.0,@aws-cdk/aws-certificatemanager=1.7.0,@aws-cdk/aws-cloudformation=1.7.0,@aws-cdk/aws-cloudfront=1.7.0,@aws-cdk/aws-cloudwatch=1.7.0,@aws-cdk/aws-ec2=1.7.0,@aws-cdk/aws-elasticloadbalancing=1.7.0,@aws-cdk/aws-elasticloadbalancingv2=1.7.0,@aws-cdk/aws-events=1.7.0,@aws-cdk/aws-iam=1.7.0,@aws-cdk/aws-kms=1.7.0,@aws-cdk/aws-lambda=1.7.0,@aws-cdk/aws-logs=1.7.0,@aws-cdk/aws-route53=1.7.0,@aws-cdk/aws-route53-targets=1.7.0,@aws-cdk/aws-s3=1.7.0,@aws-cdk/aws-s3-assets=1.7.0,@aws-cdk/aws-sns=1.7.0,@aws-cdk/aws-sqs=1.7.0,@aws-cdk/aws-ssm=1.7.0,@aws-cdk/core=1.7.0,@aws-cdk/cx-api=1.7.0,@aws-cdk/region-info=1.7.0,jsii-runtime=Python/3.7.4

